version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: sh -c "/wait && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      WAIT_HOSTS: db:5432
      WAIT_AFTER_HOSTS: 5
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db